'use strict';
let projectSetup=null;
const projectClients={codex:['Codex','Работает в папке проекта. Инструкции, skill, MCP и события среды. Hooks потребуют однократного доверия в Codex.'],claude:['Claude Code','Работает в папке проекта через CLAUDE.md и локальный инструмент. События среды пока не подключены.'],gemini:['Gemini CLI','Работает в папке проекта через GEMINI.md и локальный инструмент. События среды пока не подключены.'],generic:['Другой агент с файлами','Подключение через AGENTS.md и Python-команду. Агент должен уметь читать и менять файлы проекта.'],api:['API или MCP','Программный клиент вызывает общий контракт. Получает состояние, записывает план и запускает проверки.'],files:['Чат с файлами','Получает пакет продолжения. Передача туда и обратно остаётся ручной; команды на вашем компьютере такой чат выполнить не может.']};
async function renderProtocolSetup(){
  $('main').innerHTML=protocolAboutHTML()+protocolSetupRouteHTML('protocol-setup')+`<div class="page-header"><div class="eyebrow">НАСТРОЙКА ФРЕЙМВОРКА</div><h1>Настройте протокол под свою работу</h1><p class="intro">Определите, как ИИ должен работать: какие инструкции получать, что сохранять в памяти и какими скриптами проверять результат.</p></div><p id="protocol-ai-status" role="status">Читаем подключение ИИ…</p><div id="protocol-setup-tools" hidden><section class="card"><h2>Для какой работы нужен протокол?</h2><p>Опишите цель и условия обычным текстом. Ваш ИИ поможет разобрать, какие требования, этапы и проверки нужны для этой работы. Здесь готовится настройка; саму рабочую задачу выполняет выбранный клиент.</p><a class="primary-button" href="#onboarding">Обсудить настройку с ИИ →</a></section><div class="setup-tools"><section class="card"><h2>Правила и промпты</h2><p>Посмотрите текущие инструкции и предложите изменения с помощью подключённого ИИ. Редактор показывает точные изменения и основания перед сохранением.</p><div class="button-row"><a class="primary-button" href="#edit?path=PROTOCOL.md">Настроить правила с ИИ</a><a class="secondary-button" href="#rules">Посмотреть правила</a></div></section><section class="card"><h2>Скрипты и состав запроса</h2><p>У каждого правила можно посмотреть действующую инструкцию, поддерживающий механизм и границы проверки. Отдельно доступен код проверки черновика ответа.</p><div class="button-row"><a class="secondary-button" href="#source?path=PROTOCOL.md&amp;full=1">Инструкции и механизмы</a><a class="secondary-button" href="#source?path=check_answer.py&amp;full=1">Скрипт проверки ответа</a><a class="secondary-button" href="#source?path=docs/RUNTIME_RULES.md&amp;full=1">Как собирается запрос</a></div></section></div><section class="card"><div class="eyebrow">ИСПЫТАНИЯ НАСТРОЙКИ</div><h2>Проверьте, как работают инструкции</h2><p>Испытайте настройки на примере: проверьте ответ, перенос памяти и обнаруженные нарушения. Посмотрите фактический результат, внесите поправку и повторите затронутую проверку. Оценку смысла даёте вы.</p><div class="button-row"><a class="primary-button" href="#labs">Открыть испытания →</a><a class="secondary-button" href="#regulator">Настройка этапов и проверок</a></div></section><section class="card"><div class="eyebrow">РАБОЧИЙ КЛИЕНТ</div><h2>Подключите протокол к своему ИИ</h2><p>После настройки и испытаний выберите Codex, другого агента или чат. Получите подключение и первое сообщение; дальнейшие рабочие задачи ведите там.</p><a class="primary-button" href="#project-start">Перейти к подключению клиента →</a></section></div>`;
  try{
    const [settings,reader,adaptive]=await Promise.all([aiEditorAPI('settings'),workspaceAPI('/api/reader'),workspaceAPI('/api/adaptive')]);if(state.page!=='protocol-setup')return;
    $('protocol-setup-tools').hidden=!settings.connection_verified;
    $('protocol-setup-tools').insertAdjacentHTML('afterbegin',`<section class="card"><h2>Профиль пользователя и условия работы</h2><p>${reader.profile.configured?reader.profile.assessed?`Профиль сохранён, версия ${reader.profile.revision}.`:'Вы явно отложили оценку; необходимые понятия будут объясняться на текущем примере.':'Понимание ещё не установлено. Прежде чем выбирать способ объяснения, оцените профиль или явно отложите оценку.'} ${adaptive.profile.configured?`Условия работы сохранены, версия ${adaptive.profile.revision}.`:'Условия работы ещё не сохранены — обсудите их с ИИ ниже.'}</p><div class="button-row"><a class="primary-button" href="#reader">${reader.profile.configured?'Уточнить профиль':'Оценить профиль пользователя'} →</a><a class="secondary-button" href="#onboarding">${adaptive.profile.configured?'Уточнить условия':'Определить условия работы'} →</a></div><p class="small-note">Профиль и условия — основания для выбора инструкций. Испытания проверяют полученную настройку; рабочий клиент получает текущие подтверждённые сведения.</p></section>`);
    $('protocol-setup-tools').querySelectorAll(':scope > section')[1]?.remove();
    $('protocol-ai-status').innerHTML=settings.connection_verified?`Ваш ИИ: ${escapeHTML(settings.model)}. <a href="#settings">Изменить подключение</a>`:`Сначала <a href="#home">сохраните и проверьте свой API ИИ</a>, чтобы настраивать протокол с его помощью.`;
  }catch(error){if(state.page==='protocol-setup'&&$('protocol-ai-status'))$('protocol-ai-status').textContent=error.message;}
}
async function renderProjectStart(){
  $('main').innerHTML=protocolAboutHTML()+protocolSetupRouteHTML('project-start')+`<div class="page-header"><div class="eyebrow">РАБОЧИЙ КЛИЕНТ</div><h1>Подключение</h1><p class="intro">Выберите приложение и получите сообщение для установки протокола. Отдельный API для этого сайта не нужен. Рабочие задачи и память остаются в вашем проекте.</p></div><section class="card"><label class="form-label" for="project-goal">Что поручить агенту после подключения?</label><textarea id="project-goal" class="draft-input compact" maxlength="12000" placeholder="Необязательно. Например: изучить проект и предложить первую проверяемую задачу."></textarea><label class="form-label" for="project-client">Где будете работать? ${helpHint('Способы подключения','Выберите среду, в которой уже общаетесь с ИИ. Полный цикл доступен агенту с файлами и командами; программный клиент использует API или MCP; обычному чату нужен перенос пакетов.')}</label><select id="project-client" class="text-input">${Object.entries(projectClients).map(([k,v])=>`<option value="${k}">${escapeHTML(v[0])}</option>`).join('')}</select><p id="project-client-note" class="small-note"></p><div class="button-row"><button id="project-prepare" class="primary-button">Подготовить первое сообщение →</button></div><p id="project-setup-status" role="status"></p></section><section id="project-handoff" class="card" hidden><h2>Отправьте это в чат рабочего проекта</h2><p id="project-handoff-note"></p><textarea id="project-message" class="draft-input" readonly aria-label="Первое сообщение для ИИ"></textarea><div class="button-row"><button id="project-copy" class="primary-button">Скопировать сообщение</button><a id="project-download" class="secondary-button" href="/api/runtime-bundle" download="protocol-runtime.zip">Скачать подключение</a></div><p id="project-copy-status" role="status"></p><p>Дальше пишите задачи, замечания и «принимаю» в том же рабочем чате. План, критерии и сохранение состояния обслуживает агент.</p></section><details class="card"><summary>Дополнительно: профиль, ИИ и способы подключения</summary><p><a href="#reader">Профиль пользователя</a> · <a href="#onboarding">Условия применения</a> · <a href="#settings">Мой ИИ для настройки</a> · <a href="#connections">Подробные способы подключения</a> · <a href="#rules">Посмотреть правила</a></p><p class="small-note">API будущего приложения задайте в рабочем чате. API для настройки протокола остаётся в локальных настройках этого приложения.</p></details>`;
  $('project-prepare').disabled=true;
  try{
    const setup=await workspaceAPI('/api/runtime-installation');
    if(state.page!=='project-start')return;
    projectSetup=setup;
    projectSetup.ready=true;
    $('project-prepare').disabled=!projectSetup.ready;
    $('project-setup-status').textContent=setup.configuration?'Подключение готово. Сохранённые условия и профиль будут приложены; их можно уточнить в рабочем чате.':'Подключение готово. Профиль и условия можно определить вместе с агентом в рабочем чате.';
  }catch(error){if($('project-setup-status'))$('project-setup-status').textContent=error.message;}
  if(!$('project-goal'))return;
  $('project-goal').value=localStorage.getItem('protocol-project-goal')||'';
  $('project-client').value=localStorage.getItem('protocol-project-client')||'codex';updateProjectClient();
}
function updateProjectClient(){const target=$('project-client-note');if(target)target.textContent=projectClients[$('project-client').value][1];if($('project-handoff'))$('project-handoff').hidden=true;}
function prepareProjectMessage(){
  if(!projectSetup){$('project-setup-status').textContent='Дождитесь чтения подключения.';return;}
  if(!projectSetup.ready){$('project-setup-status').textContent='Сначала сохраните профиль и условия работы.';return;}
  const goal=$('project-goal').value.trim()||'Проверь подключение протокола и прочитай текущее состояние проекта. Затем уточни у меня рабочую задачу.',client=$('project-client').value;
  localStorage.setItem('protocol-project-goal',goal);localStorage.setItem('protocol-project-client',client);
  let setup;
  if(client==='files')setup='Получишь архив подключения. Если проекта ещё нет, помоги создать папку, распаковать туда архив и один раз выполнить py -3 install_protocol.py install --client files --project . В результате появится .protocol/PACKAGE.json. Попроси этот один актуальный пакет из рабочего проекта; продолжай по его context и skill. Возвращай пакет с operations для импорта. Не выдавай отчёт за выполненную на моём компьютере проверку. Дальше необходим только перенос пакетов между чатом и проектом.';
  else if(client==='api')setup=`Подключи общий runtime к текущему рабочему проекту командой ${projectSetup.commands.api}. Если исходная папка недоступна, распакуй приложенный protocol-runtime.zip и выполни python install_protocol.py install --client api --project . Используй JSON CLI, stdio MCP или локальный HTTP: python .protocol/engine/runner.py serve --project . Для MCP: python .protocol/engine/runner.py mcp --project . Контракт описан в .protocol/skills/protocol-work/references/contract.md. Не запрашивай отдельный ключ ИИ для атласа.`;
  else setup=`Ты работаешь в открытом проекте. Подключи к нему протокол командой ${projectSetup.commands[client]}. Выполняй её в текущей папке проекта. Если исходная папка протокола недоступна, я приложу protocol-runtime.zip: распакуй его в проект и выполни python install_protocol.py install --client ${client} --project . Сохрани существующие настройки проекта. Для Codex сообщи об однократном доверии hooks, если клиент запросит его.`;
  $('project-message').value=setup+(projectSetup.configuration?'\n\nСохранённая настройка протокола и профиль понимания:\n'+JSON.stringify(projectSetup.configuration,null,2):'\n\nПредварительные профиль и условия не заданы; уточняй их в рабочем чате по мере необходимости.')+'\n\nМоя задача:\n'+goal+'\n\nПрочитай установленный skill и текущее context. Если настройка приложена, проверь её версии в .protocol/configuration.json. Если в рабочем проекте уже есть другой профиль или условия, покажи различие и сохрани прежнее основание до решения человека. Сам выдели тип, объём, сложность, этапы, зависимости и проверяемые критерии. Уточни только сведения, без которых нельзя продолжить. Затем выполняй уже разрешённую работу, записывая проверки и результат каждого этапа через runtime. Отдельных форм в атласе не нужно. Решение человека фиксируй только по моему фактическому отзыву; красивую картинку не считай доказательством правильности данных или готовности приложения. При новом сеансе восстанови состояние из проекта.';
  $('project-download').href='/api/runtime-bundle?configuration_sha256='+encodeURIComponent(projectSetup.configuration_sha256);
  $('project-handoff-note').textContent=client==='files'?'Скачайте архив. Для обычного чата нужен перенос пакетов; текущее состояние всегда остаётся в проекте.':'Откройте рабочий проект в выбранном приложении и вставьте сообщение. Агент выполнит установку; архив нужен, если папка протокола недоступна.';
  $('project-handoff').hidden=false;$('project-setup-status').textContent='Сообщение готово.';$('project-handoff').scrollIntoView({behavior:'smooth',block:'start'});
}
async function renderProjectState(){$('main').innerHTML='<div id="atlas-project-dashboard"></div>';await mountProtocolDashboard($('atlas-project-dashboard'),'/api/project-runtime/');}
document.addEventListener('change',event=>{if(event.target.id==='project-client')updateProjectClient();});
document.addEventListener('input',event=>{if(event.target.id==='project-goal'){localStorage.setItem('protocol-project-goal',event.target.value);if($('project-handoff'))$('project-handoff').hidden=true;}});
document.addEventListener('click',async event=>{if(event.target.closest('#project-prepare'))prepareProjectMessage();if(event.target.closest('#project-copy')){try{await navigator.clipboard.writeText($('project-message').value);$('project-copy-status').textContent='Скопировано. Вставьте в рабочий чат.';}catch(error){$('project-message').select();$('project-copy-status').textContent='Выделено. Нажмите Ctrl+C.';}}});
