'use strict';
const protocolStatusNames={planning:'Агент составляет план',running:'В работе',ready:'Можно начинать',blocked:'Ожидает входной результат',verified:'Проверено',accepted:'Принято человеком',awaiting_review:'Готово к вашему отзыву',needs_recheck:'Нужна повторная проверка',interrupted:'Работа прервана',revise:'Есть замечания',rejected:'Отклонено'};
const pdEscape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function pdBadge(status){return `<span class="pd-badge ${['needs_recheck','blocked','rejected','interrupted','revise'].includes(status)?'pd-problem':''}">${pdEscape(protocolStatusNames[status]||status)}</span>`;}
function pdEvidence(stage,taskId){
  const e=stage.evidence_summary||{},labels={passed:'Проверено в указанной области',failed:'Обнаружено несоответствие',stale:'Свидетельство устарело',unsupported:'Не поддерживается',not_checked:'Не проверено',not_established:'Не установлено'};
  return `<section class="pd-evidence"><h4>Границы проверки</h4><p>${e.mode_explicit?'Режим выбран явно':'Режим явно не выбран; используются прежние критерии'}</p><dl>${[['formal_conformance','Формальное соответствие'],['premise_truth','Истинность посылок'],['source_translation','Верность перевода источника'],['actual_model_logic_use','Внутреннее применение логики моделью'],['stage_criteria','Критерии этапа']].map(([key,title])=>`<dt>${title}</dt><dd>${pdEscape(labels[e[key]]||'Не проверено')}</dd>`).join('')}</dl><p class="pd-muted">Контроль действует внутри зарегистрированного этапа. Произвольные внешние действия и защита среды этим статусом не подтверждаются.</p><details><summary>Изменить режим проверки</summary><label>Режим <select data-verification-mode>${[['criteria','По критериям этапа'],['formal','Формальная логика'],['empirical','Исполняемая предметная проверка'],['manual','Содержательная оценка']].map(([key,title])=>`<option value="${key}"${e.mode===key?' selected':''}>${title}</option>`).join('')}</select></label><label>Основание изменения <input data-verification-reason type="text" maxlength="2000"></label><p class="pd-muted">Изменение потребует новых проверок. Формальный режим требует подключённого договора логики.</p><button data-verification-save data-task="${pdEscape(taskId)}" data-stage="${pdEscape(stage.id)}">Применить режим</button></details></section>`;
}
function pdStage(stage,taskId){return `<article class="pd-stage"><div class="pd-row"><h3>${pdEscape(stage.title)}</h3>${pdBadge(stage.status)}</div><dl><dt>Тип</dt><dd>${pdEscape(stage.type)}</dd><dt>Объём</dt><dd>${pdEscape(stage.volume)}</dd><dt>Сложность</dt><dd>${pdEscape(stage.complexity)}</dd><dt>Входы</dt><dd>${pdEscape(stage.requires.join(', ')||'Начальный этап')}</dd><dt>Переход</dt><dd>${stage.gate==='human'?'После вашего принятия':'После успешных проверок'}</dd></dl>${stage.recheck_reasons?.length?`<p>${pdEscape(stage.recheck_reasons.join('; '))}</p>`:''}<ul>${stage.criteria.map(c=>{const check=[...stage.checks].reverse().find(x=>x.criterion_id===c.id);return `<li>${pdEscape(c.text)} — ${check?(check.passed?'проверка пройдена':'проверка не пройдена'):'ещё не проверено'} <small class="pd-muted">(${pdEscape(c.kind)})</small></li>`;}).join('')}</ul>${stage.result?`<p>${pdEscape(stage.result.summary)}</p><p class="pd-muted">Файлы: ${pdEscape(Object.keys(stage.result.artifacts).join(', ')||'Без файлов')}</p>`:''}${pdEvidence(stage,taskId)}<details><summary>Свидетельства и версии</summary>${stage.checks.map(check=>`<p><strong>${pdEscape(check.criterion_id)}</strong> · ${pdEscape(check.origin)} · ${pdEscape(check.at)}</p><pre>${pdEscape(JSON.stringify(check.evidence,null,2))}</pre><pre>${pdEscape(JSON.stringify(check.artifacts,null,2))}</pre>`).join('')||'<p>Свидетельств пока нет.</p>'}</details></article>`;}
async function mountProtocolDashboard(container,base='/protocol/'){
  container.classList.add('protocol-dashboard');
  container.innerHTML='<div class="pd-top"><div><h1>Состояние рабочего проекта</h1><p class="pd-muted">Задачи и замечания обсуждайте в чате своего ИИ. Здесь можно посмотреть, что произошло.</p></div><button id="pd-refresh">Обновить</button></div><p id="pd-message" role="status"></p><div id="pd-content">Загружаем состояние…</div>';
  let state;
  async function request(action,payload){const response=await fetch(base+action,payload?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}:{});const value=await response.json();if(!response.ok)throw Error(value.error||'Не удалось прочитать состояние');return value;}
  async function refresh(){try{state=await request('status');if(!container.isConnected)return;const content=container.querySelector('#pd-content');if(!state.installed){content.innerHTML='<p class="pd-empty">К этой папке протокол пока не подключён. Подключите его в рабочем проекте; состояние будет храниться рядом с вашим приложением.</p>';return;}
      const diagnostic=state.diagnostics||{},events=diagnostic.observed_host_events||{};
      content.innerHTML=`<div class="pd-row"><h2>${pdEscape(state.name)}</h2><span class="pd-muted">Версия ${state.revision}</span></div><div class="pd-grid"><div class="pd-card"><div class="pd-metric">${state.tasks.length}</div>задач</div><div class="pd-card"><div class="pd-metric">${((diagnostic.database_bytes||0)/1024).toFixed(1)} КБ</div>состояние и история</div><div class="pd-card"><div class="pd-metric">${Object.values(events).reduce((a,b)=>a+b,0)}</div>наблюдаемых событий среды</div></div>${state.tasks.length?state.tasks.slice().reverse().map(task=>`<section class="pd-card"><div class="pd-row"><h2>${pdEscape(task.goal)}</h2>${pdBadge(task.status)}</div><p class="pd-muted">Следующий этап: ${pdEscape(task.next_stage||'обсудить результат в чате')}</p>${task.interruption&&task.status==='interrupted'?`<p>${pdEscape(task.interruption.reason)}</p>`:''}${task.stages.map(stage=>pdStage(stage,task.id)).join('')}${task.feedback.length?`<details><summary>Замечания и принятие</summary>${task.feedback.map(f=>`<p>${pdEscape(f.message)} <small>· ${pdEscape(f.outcome)} · ${pdEscape(f.origin)}</small></p>`).join('')}</details>`:''}</section>`).join(''):'<p class="pd-empty">Задач пока нет. Опишите цель в рабочем чате обычным текстом; агент составит план.</p>'}<section class="pd-card"><h2>Подключения и работа механизмов</h2><p class="pd-muted">Наличие настройки и факт срабатывания показаны отдельно.</p><div class="pd-scroll"><table><thead><tr><th>Подключение</th><th>Заявленные возможности</th><th>Последняя настройка</th></tr></thead><tbody>${state.connections.map(c=>`<tr><td>${pdEscape(c.client)}</td><td>${pdEscape(Object.keys(c.capabilities).filter(k=>c.capabilities[k]).join(', '))}</td><td>${pdEscape(c.last_seen)}</td></tr>`).join('')}</tbody></table></div><p>${Object.keys(events).length?pdEscape(Object.entries(events).map(([k,v])=>k+': '+v).join(' · ')):'Событий среды ещё нет. Для Codex нужно однократное доверие проектным hooks; другие клиенты работают через инструкции и инструменты.'}</p></section><section class="pd-card"><h2>Хранение</h2><p>Текущие результаты, проверки и замечания сохраняются. История содержит изменения состояния; полные диалоги, тела вызовов инструментов и копии выходных файлов не записываются.</p><label for="pd-retention">Служебные события среды</label> <select id="pd-retention">${[0,200,2000,10000].map(v=>`<option value="${v}">${v===0?'Не хранить':('Последние '+v)}</option>`).join('')}</select> <button id="pd-save-storage">Сохранить</button><p class="pd-muted">Изменение лимита применяется при следующем событии. Архивировать результаты можно обычным способом вместе с проектом.</p><p><a href="${base}export" download="protocol-continuation.json">Скачать пакет продолжения</a></p></section>`;
      content.querySelectorAll('[data-verification-save]').forEach(button=>{button.onclick=async()=>{const section=button.closest('.pd-evidence');const reason=section.querySelector('[data-verification-reason]').value.trim();if(!reason){container.querySelector('#pd-message').textContent='Укажите основание изменения режима.';return;}button.disabled=true;try{await request('set_verification',{expected_revision:state.revision,task_id:button.dataset.task,stage_id:button.dataset.stage,mode:section.querySelector('[data-verification-mode]').value,reason});await refresh();container.querySelector('#pd-message').textContent='Режим сохранён; нужны новые проверки.';}catch(error){button.disabled=false;container.querySelector('#pd-message').textContent=error.message;}};});
      const select=container.querySelector('#pd-retention'),limit=diagnostic.storage_policy?.host_event_limit??2000;
      if(![0,200,2000,10000].includes(limit))select.add(new Option('Последние '+limit,limit));select.value=limit;
      const save=container.querySelector('#pd-save-storage');
      const experience=state.experience||[];
      content.insertAdjacentHTML('beforeend',`<section class="pd-card"><h2>Опыт и изменение нагрузки</h2><p class="pd-muted">Учитываются фактические проверки и замечания для того же клиента, модели и типа задачи. Неизвестная модель не участвует в переносе опыта.</p>${experience.length?experience.map(row=>`<h3>${pdEscape(row.client)} · ${pdEscape(row.model)} · ${pdEscape(row.type)}</h3><p>Принято: ${row.accepted} · Ошибок проверок: ${row.failed_checks} · Поправок: ${row.corrections}</p><p>${pdEscape(row.recommendation)}</p>`).join(''):'<p>Подтверждённого опыта с известной моделью пока нет. Пределы нагрузки автоматически не повышались.</p>'}</section>`);
      save.insertAdjacentHTML('beforebegin',`<p><label for="pd-workflow-retention">История изменений</label> <select id="pd-workflow-retention">${[100,500,2000,10000].map(v=>`<option value="${v}">Последние ${v}</option>`).join('')}</select></p><p><label for="pd-output">Вывод проверочных команд</label> <select id="pd-output"><option value="none">Только итог и контрольная сумма</option><option value="errors">Текст только при ошибке</option><option value="all">Текст каждой проверки</option></select></p>`);
      const history=container.querySelector('#pd-workflow-retention'),historyLimit=diagnostic.storage_policy?.workflow_event_limit??2000;
      if(![100,500,2000,10000].includes(historyLimit))history.add(new Option('Последние '+historyLimit,historyLimit));history.value=historyLimit;
      container.querySelector('#pd-output').value=diagnostic.storage_policy?.command_output??'errors';
      save.onclick=async()=>{try{await request('storage',{expected_revision:state.revision,host_event_limit:Number(select.value),workflow_event_limit:Number(history.value),command_output:container.querySelector('#pd-output').value});await refresh();container.querySelector('#pd-message').textContent='Параметры хранения сохранены.';}catch(error){container.querySelector('#pd-message').textContent=error.message;}};
    }catch(error){if(container.isConnected)container.querySelector('#pd-message').textContent=error.message;}}
  container.querySelector('#pd-refresh').onclick=refresh;await refresh();
}
if(document.getElementById('protocol-dashboard'))mountProtocolDashboard(document.getElementById('protocol-dashboard'));
